##笔记本的环境设置
server:
    #tomcat端口  比如http://{ip}:{port}{/context-path}中的{port} 纯数字
    port: 18080
common:
    datasource:
        #mysql url连接信息
        url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&userSSL=true&serverTimezone=Hongkong&zeroDateTimeBehavior=CONVERT_TO_NULL
        #数据库用户名
        username: root
        #数据库密码
        password:
        #mysql8新驱动名称
        driverClassName: com.mysql.cj.jdbc.Driver

spring:
    thymeleaf:
        cache: false
    redis:
        clusters:
            #redis支持集群模式(需要参考文档自行打开) 也支持单机(配置一个即可) 配置规则：节点的ip:port,ip:port 逗号分隔多个
            nodes: localhost:6379
            #最大连接时间 具体参考JedisCluster官方文档
            connectionTimeout: 5000
            soTimeout: 5000
            maxAttempts: 3
        #不允许redis密码为空字符串 可以不设置 您可以使用"1234"
        password:
        #所有的redis 缓存都会加入下面的前缀 方便管理
        keyPrefix: crm-admin.
    #druid管理后台 http://localhost:18080/crm-admin/druid/ 可以查看数据源的状态 账号/密码：admin/123456
    monitor:
        druid:
            userName: admin
            password: 123456
            allowIps: 127.0.0.1
            denyIps: 10.1.1.1
            filters: stat,log4j
    devtools:
        restart:
            #是否开启热部署 另外需要配置ide的配置一同生效 参考这篇文章 https://blog.csdn.net/boywcx/article/details/81164411
            enabled: false

magicalcoder:
    file:
        upload:
            #由于spring boot是jar方式执行，无法自动映射上传文件访问地址，采取单独映射方法
            mapping:
                #文件要上传到的硬盘路径 例如 windows: /E:/tmp/test/  linux: /home/web/file/upload/ 如果不设置 则会自动查找classpath路径下的upload
                uploadDiskFolder:
                #虚拟访问映射地址 请尽量不要改动 AdminCommonFileRestController里面有根据这个返回给前端 /.*/格式 最后1个/别忘记了
                requestPrefix: /upload/
    #超级管理员账号名称 密码默认：magicalcoder
    superUserName: magicalcoder
    cors:
        #      跨域 支持哪些同源域名 逗号分隔多个 你可以配置 http://localhost:18088,http://www.magicalcoder.com
        allowOrigin:
